### ISSUE TITLE
Add schema validations for the parsers

### ISSUE THREAD

**Issue by bill-ahmed** [nikel-api/nikel-parser#4]
Currently all output JSON is left un-validated. Introducing some kind of schema validation would let us catch errors with the output much earlier on, such as if UofT decided to modify their APIs or web page layouts. 

Also, adding these schema could provide a stronger back-bone for when the parsers are refactored/updated to meet new requirements (they could be incorporated into some sort of test suite later on). 

An example of a library that may do the job: https://pypi.org/project/schema/

The schema don't have to be particularly complicated, it could start with some simple validations on fields that we expect to always be present with a specific data type/format.

**Comment by darenliang** [comment]
Great idea.

I think a good place to put the schema validation and tests is just before the data gets written to disk.

**Comment by bill-ahmed** [comment]
Yep I was thinking that as well. 

Although an edge consideration might be that if there is an error, do we avoid writing anything to disk? Maybe letting it write to disk and then running the validations separately would let us better debug it (because we'll have the output JSON to play around with).

Let me know what your thoughts are.

**Comment by darenliang** [comment]
We probably should allow writes, but the data should be clearly indicated that it is malformed in some way.

**Comment by darenliang** [comment]
After thinking about the problem, this change will actually be extremely useful. Once we figure out which fields should be what type (eg. string, string or null, etc.), we could update the schema in the documentation to give a better sense of how developers should handle `null` in this API. Additionally, the node.js will be updated to reflect these changes so that developers using Typescript will be warned that certain fields are nullable.
