### ISSUE TITLE
Buildings schema can have multiple null values

### ISSUE THREAD

**Issue by bill-ahmed** [nikel-api/nikel-parser#5]
When writing up some validations, i've noticed that `buildings.json` can have null values for many fields, such as `tags`, `code`, `short_name`, all fields in `address`, and others.

Was wondering if this is to be expected since it doesn't seem to be indicated in the docs?

**Comment by bill-ahmed** [comment]
If this is indeed a bug, a quick fix would be to simply change
```python
building['id'] = self.process_field(el, 'id')
building['code'] = self.process_field(el, 'code')
```
to something like
```python
building['id'] = self.process_field(el, 'id') or ""
building['code'] = self.process_field(el, 'code') or ""
```
so the fields default to empty string, for all the fields that `null` may be present for.

**Comment by darenliang** [comment]
This is a long-standing problem which I don't believe to have an easy solution.

Using `null` is indeed unsafe in an API and it is possible to use an empty string or zero value as the default value.

As in the docs, the reason why I don't document this problem is that I believe the most common consumer of this API is Node.js or browser applications. Javascript "sort of" embraces the `null` value.

I've decided that the most idiomatic solution is to leave the data be as it is. And for people who are using the API, they should either handle the nulls or unpack the JSON response into the default value of their choice.

**Comment by bill-ahmed** [comment]
ahh gotcha, thanks for clearing that up!
